Add spotbugs filter file
ExpediaGroup/eg-oss-plugin-config pull request #3
Opened 2019-08-06 07:31 UTC by cmathiesen

2019-08-06 18:28 UTC, massdosage requested changes
Bump minor version since we're adding a feature. Also please add a line to the changelog.

2019-08-06 18:28 UTC, massdosage commented on src/main/resources/spotbugs/hotels-spotbugs-exclude.xml
> +<!-- these bugs/files/etc won't be reported by findbugs -->
Rename this file to `eg-spotbugs-exclude.xml`

2019-08-06 18:28 UTC, massdosage commented on src/main/resources/spotbugs/hotels-spotbugs-exclude.xml
> +<!-- these bugs/files/etc won't be reported by findbugs -->
findbugs -> spotbugs

2019-08-07 19:19 UTC, massdosage approved these changes

2019-08-08 09:32 UTC, patduin approved these changes

2019-08-08 18:40 UTC, massdosage approved these changes

2019-08-08 18:40 UTC, merged